#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

# Usa o watchfiles para monitorar arquivos .py e .html e reiniciar o servidor automaticamente
exec watchfiles "python manage.py runserver_plus 0.0.0.0:8000 --reloader-type stat"